# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OZ8WDdjYVTU42Z1ToT8axCyNGZbTxL3m
"""

!pip install simpy
import simpy
import random
import statistics
import networkx as nx
import matplotlib.pyplot as plt

import random
import simpy
import networkx as nx
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

TOTAL_PIECES = 10  # 总共的文件块数 / Total number of file pieces
SIMULATION_TIME = 100  # 模拟的总时长 / Total simulation time

class Strategy:
    @staticmethod
    def equal_distribution_strategy(peer, target_peer_id):
        """根据当前的请求数，均匀分配上传带宽 / Evenly distribute upload bandwidth based on current number of requests"""
        number_of_requests = peer.current_requests
        available_bandwidth_per_request = peer.upload_speed / max(1, number_of_requests)  # 防止除0
        return available_bandwidth_per_request

    @staticmethod
    def tit_for_tat(peer, target_peer_id):
        """根据对方从当前用户得到的总下载量占比分配带宽 / Allocate bandwidth based on the ratio of what the target peer has uploaded"""
        total_downloaded = peer.total_downloaded
        if total_downloaded == 0:
            # 如果当前用户还没有下载任何东西，则按平等策略分配
            return Strategy.equal_distribution_strategy(peer, target_peer_id)

        # 获取目标 peer 从当前 peer 这里下载的总量
        download_from_peer = peer.upload_history.get(target_peer_id, 0)
        # 按照 tit-for-tat 策略计算带宽占比
        bandwidth_ratio = download_from_peer / total_downloaded
        available_bandwidth = bandwidth_ratio * peer.upload_speed
        return available_bandwidth

    def random_bandwidth_distribution(peer):
        """随机生成带宽分配并保存到 bandwidth_allocation 中 / Randomly generate bandwidth allocation and save it"""
        total_bandwidth = peer.upload_speed
        number_of_peers = len(peer.peers)
        allocations = {}

        # 随机分配带宽给每个请求的 peer
        for p in peer.peers:
            allocation = random.uniform(0, total_bandwidth / max(1, number_of_peers))
            allocations[p.id] = allocation
            total_bandwidth -= allocation

        # 保存分配到 peer 的 bandwidth_allocation 中
        peer.bandwidth_allocation = allocations

    @staticmethod
    def allocate_bandwidth(peer, target_peer_id):
        """根据带宽分配表分配带宽，如果表为空则随机分配 / Allocate bandwidth based on existing allocation, or randomly if none exists"""
        if not peer.bandwidth_allocation:
            Strategy.random_bandwidth_distribution(peer)

        # 按照分配表分配带宽
        return peer.bandwidth_allocation.get(target_peer_id, 0)

class Peer:
    def __init__(self, env, id, upload_speed, download_speed, animation, strategy):
        self.env = env
        self.id = id
        self.upload_speed = upload_speed  # 上传带宽 / Upload bandwidth
        self.download_speed = download_speed  # 下载带宽 / Download bandwidth
        self.file_pieces = set()  # 当前拥有的文件块 / File pieces currently owned
        self.peers = []  # 其他对等节点 / Other peers
        self.upload_resource = simpy.Resource(env, capacity=upload_speed)  # 上传带宽作为资源 / Upload bandwidth as a resource
        self.current_requests = 0  # 当前的请求数 / Current number of requests
        self.upload_history = {}  # 记录上传历史 / Dictionary to track upload history
        self.total_downloaded = 0  # 记录总共下载的文件大小 / Total downloaded file size
        self.bandwidth_allocation = {}  # 带宽分配，记录对每个 peer 的分配情况 / Dictionary to store bandwidth allocation
        self.env.process(self.run())
        self.animation = animation  # 引入 Animation 对象
        self.strategy = strategy  # 当前 peer 的带宽分配策略

    def add_peer(self, peer):
        self.peers.append(peer)

    def request_piece(self, piece, target):
        """请求特定文件块并动态调整带宽 / Request a specific file piece and dynamically adjust bandwidth"""
        if piece in target.file_pieces:
            print(f'Time {self.env.now}: Peer {self.id} requests file piece {piece} from Peer {target.id}')

            with target.upload_resource.request() as req:
                target.current_requests += 1
                piece_size = Peer.piece_size
                downloaded = 0  # 初始化已下载部分 / Initialize downloaded portion

                while downloaded < piece_size:
                    # 根据 target peer 的策略分配带宽
                    if target.strategy == "tit_for_tat":
                        available_bandwidth_per_request = Strategy.tit_for_tat(target, self.id)
                    elif target.strategy == "random_bandwidth":
                        available_bandwidth_per_request = Strategy.allocate_bandwidth(target, self.id)
                    else:
                        available_bandwidth_per_request = Strategy.equal_distribution_strategy(target, self.id)

                    data_per_step = available_bandwidth_per_request * 0.1  # 假设时间步为 0.1 秒

                    downloaded += data_per_step
                    yield self.env.timeout(0.1)

                    # 计算进度百分比
                    progress_percentage = (downloaded / piece_size) * 100
                    print(f'Time {self.env.now:.1f}: Peer {self.id} has downloaded {progress_percentage:.1f}% of file piece {piece}')

                    # 调用动画更新进度
                    self.animation.update_progress((target.id, self.id), round(progress_percentage, 2))

                target.current_requests -= 1
                self.file_pieces.add(piece)
                print(f'Time {self.env.now:.1f}: Peer {self.id} completed download of file piece {piece}')

                # 记录 target 传输给当前 peer 的总文件大小
                if target.id not in self.upload_history:
                    self.upload_history[target.id] = 0
                self.upload_history[target.id] += piece_size  # 将传输的文件块大小加入历史记录

                # 更新总下载文件大小
                self.total_downloaded += piece_size
                #print(f"Peer {self.id} received {piece_size} MB from Peer {target.id}. Total received: {self.upload_history[target.id]} MB")
                #print(f"Peer {self.id} has downloaded a total of {self.total_downloaded} MB")

        else:
            print(f"Time {self.env.now:.1f}: Peer {self.id} found that Peer {target.id} no longer has file piece {piece}")


    def run(self):
        while True:
            if len(self.file_pieces) == TOTAL_PIECES:
                break
            yield self.env.timeout(1)

            missing_pieces = set(range(TOTAL_PIECES)) - self.file_pieces
            if not missing_pieces:
                break

            request_tasks = []
            requesting_pieces = set()

            for piece in missing_pieces:
                if piece in requesting_pieces:
                    continue
                shuffled_peers = self.peers[:]
                random.shuffle(shuffled_peers)

                for target_peer in shuffled_peers:
                    if piece in target_peer.file_pieces:
                        # 在找到目标节点后立即连接，并开始请求
                        self.animation.connect_peers(target_peer.id, self.id)
                        request_tasks.append(self.env.process(self.request_piece(piece, target_peer)))
                        requesting_pieces.add(piece)
                        break

            if request_tasks:
                yield self.env.all_of(request_tasks)

class Animation:
    def __init__(self, num_peers):
        self.num_peers = num_peers
        self.G = nx.DiGraph()
        self.pos = None
        self.edge_labels = {}
        self.fig, self.ax = plt.subplots()  # 创建画布
        self.updates = []  # 用于存储每一帧的更新（边和进度）

    def generate_peers(self):
        """生成Peer节点"""
        self.G.add_node(0, label='Peer 0')
        for i in range(1, self.num_peers):
            self.G.add_node(i, label=f'Peer {i}')
        self.pos = nx.circular_layout(self.G)

    def connect_peers(self, from_peer, to_peer):
        """为成功请求的两个Peer之间连线"""
        if not self.G.has_edge(from_peer, to_peer):
            self.G.add_edge(from_peer, to_peer, progress=0)  # 为两个成功请求的节点添加一条边
        self.edge_labels[(from_peer, to_peer)] = '0%'

    def update_progress(self, edge, progress):
        """更新指定边的进度，并在动画中展示"""
        from_peer, to_peer = edge
        if self.G.has_edge(from_peer, to_peer):
            self.G[from_peer][to_peer]['progress'] = progress
            self.edge_labels[(from_peer, to_peer)] = f'{progress}%'

        # 每次更新后将状态存储到 updates 列表中
        self.updates.append((edge, progress))

    def animate(self, i):
        """逐帧更新图像的动画函数"""
        self.ax.clear()

        # 绘制节点和边
        nx.draw(self.G, self.pos, with_labels=True, labels=nx.get_node_attributes(self.G, 'label'),
                node_color='lightblue', node_size=1000, ax=self.ax)
        nx.draw_networkx_edges(self.G, self.pos, ax=self.ax)

        # 逐帧应用进度更新
        if i < len(self.updates):
            edge, progress = self.updates[i]
            from_peer, to_peer = edge
            self.edge_labels[(from_peer, to_peer)] = f'{progress}%'

        # 绘制边上的进度标签
        nx.draw_networkx_edge_labels(self.G, self.pos, edge_labels=self.edge_labels, ax=self.ax)

    def save_animation(self, filename='animation.mp4', frames=10, interval=1000):
        frame_list = frames
        anim = FuncAnimation(self.fig, self.animate, frames=frame_list, interval=interval, repeat=False)
        anim.save(filename, writer='ffmpeg')
        print(f"Animation saved as {filename}")

def run_simulation(num_peers):
    env = simpy.Environment()
    peers = []
    animation = Animation(num_peers)  # 创建动画实例

    Peer.file_size = random.uniform(10, 20)  # 假设文件大小在10MB到20MB之间
    Peer.piece_size = Peer.file_size / TOTAL_PIECES

    animation.generate_peers()

    # 创建多个对等节点
    for i in range(num_peers):
        upload_speed = random.uniform(1, 5)
        download_speed = random.uniform(30, 50)
        # 随机分配策略，包括随机带宽策略
        strategy = random.choice(["random_bandwidth", "tit_for_tat", "equal_distribution_strategy"])
        peer = Peer(env, i, upload_speed, download_speed, animation, strategy)  # 将动画和策略传递给 Peer 类
        peers.append(peer)

        if i == 0:
            peer.file_pieces = set(range(TOTAL_PIECES))  # 种子节点拥有所有文件块
        else:
            num_pieces = random.randint(0, TOTAL_PIECES - 1)
            peer.file_pieces = set(random.sample(range(TOTAL_PIECES), num_pieces))

    # 连接所有对等节点
    for peer in peers:
        for other_peer in peers:
            if peer != other_peer:
                peer.add_peer(other_peer)

    # 运行模拟
    env.run(until=SIMULATION_TIME)

    # 保存动画为 mp4
    animation.save_animation(filename='animation.mp4', frames=100, interval=100)
# 运行模拟
run_simulation(5)
